server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/vle-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      # habilita para que todas as alterações feitas no código refletem no banco de dados
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbd:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
